receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317

# extensions:
#  zpages:
#    endpoint: 127.0.0.1:55679

exporters:
  debug:
    verbosity: detailed

service:
  #extensions: [zpages]
  telemetry:
    metrics:
      level: none
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
