/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project_template;

import org.json.JSONObject;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        JSONObject jo = new JSONObject("{ \"abc\" : \"def\" }");
        System.out.println(jo);
    }
}
